FROM ubuntu:latest
RUN apt update -y && apt upgrade -y
RUN apt install sudo nano python3 pip python3-dev default-libmysqlclient-dev build-essential wget -y
RUN wget 'https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh' && chmod 755 wait-for-it.sh
RUN pip install django mysqlclient django-environ tzdata
RUN django-admin startproject django_app
WORKDIR /django_app
RUN python3 manage.py startapp show
COPY ./django/django_files/settings.py /django_app/django_app/
COPY ./django/django_files/urls_app.py /django_app/show/urls.py
COPY ./django/django_files/views.py /django_app/show/views.py
COPY ./django/django_files/urls.py /django_app/django_app/urls.py
COPY ./django/django_files/models.py /django_app/show/models.py
COPY ./django/django_files/index.html /django_app/show/templates/show/index.html
COPY ./django/django_files/.env /django_app/
COPY ./django/django_files/admin.py /django_app/show/admin.py
COPY ./django/django_files/startup.sh /
RUN chmod 744 /startup.sh
CMD ["/wait-for-it.sh", "mysql:3306","--", "/startup.sh"]
